version: '3'
services:
  julia:
    build:
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - [gpu]
    environment:
      - DISPLAY=$DISPLAY
    networks:
      - host